import StreamVideoProvider from '@/providers/StreamClientProvider'
import { Metadata } from 'next';
import React, { ReactNode } from 'react'

export const metadata: Metadata = {
  title: "Video Calling App",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/log.svg'
  }
};
const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <main>
        <StreamVideoProvider>
          {children}
        </StreamVideoProvider>      
    </main>
  )
}

export default RootLayout